config/routes.rb
Kadri::Application.routes.draw do
  resources :skills, only: 'show' do
    get :autocomplete_skill_name, :on => :collection
  end

  resources :resumes
  resources :vacancies

  devise_for :users
  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Resume, :user_id => user.id
      can :manage, Vacancy, :user_id => user.id
    end
  end
end

app/models/resume.rb
# encoding: UTF-8
class Resume < ActiveRecord::Base
  require 'common_behavior'
  include CommonBehavior
  attr_accessible :email, :phone, :name, :salary, :status, :skill_list

  validates_format_of :name, :with => /\A[а-яА-ЯёЁ]+\s+[а-яА-ЯёЁ]+\s+[а-яА-ЯёЁ]+$\Z/i, message: "Фамилия Имя Отчество, только русские буквы"

  scope :active, where(status: true).order('salary asc')

  def fully_matched_resumes
    self.fully_matched.active
  end

  def partially_matched_resumes

    self.partially_matched.active
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name

  has_many :resumes, :through => :skillings, :source => :skillable, :source_type => "Resume"
  has_many :vacancies, :through => :skillings, :source => :skillable, :source_type => "Vacancy"
  has_many :skillings

  def self.valid_skills
    skill_ids = Skilling.all.map(&:skill_id).uniq
    Skill.find skill_ids
  end
end

app/models/skilling.rb
class Skilling < ActiveRecord::Base

  belongs_to :skillable, :polymorphic => true
  belongs_to :skill

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_format_of :name, :with => /\A[а-яА-ЯёЁ]+\s+[а-яА-ЯёЁ]+\s+[а-яА-ЯёЁ]+$\Z/i

  has_many :resumes, :dependent => :destroy
  has_many :vacancies, :dependent => :destroy

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  require 'common_behavior'
  include CommonBehavior
  attr_accessible :email, :phone, :duedate, :name, :salary, :skill_list

  scope :active, where('duedate >= ?', Date.today).order('salary desc')

  def fully_matched_vacancies
    self.fully_matched.active
  end

  def partially_matched_vacancies
    self.partially_matched.active
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, except: [:index, :show]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
    @resumes = Resume.active.reorder('created_at desc').last(10)
    @vacancies = Vacancy.active.reorder('created_at desc').last(10)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  load_and_authorize_resource :except => :index
  autocomplete :skill, :name
  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.active
    @resumes += current_user.resumes if current_user
    @resumes.uniq!
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    # @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.js {}
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update

    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.js { render :create }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  autocomplete :skill, :name

  def show
    @skill = Skill.find(params[:id])
  end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  load_and_authorize_resource :except => :index
  autocomplete :skill, :name
  # GET /vacancies
  # GET /vacancies.json
  def index
    @vacancies = Vacancy.active
    @vacancies += current_user.vacancies if current_user
    @vacancies.uniq!
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacancies }
    end
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  # GET /vacancies/new.json
  def new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.js {}
        format.json { render json: @vacancy, status: :created, location: @vacancy }
      else
        format.html { render action: "new" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vacancies/1
  # PUT /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update_attributes(params[:vacancy])
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.js { render :create }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
  def skills_label skills, close=false
    prepend = "<span class='label label-success'>"
    prepend += "<a class='close'>&times;</a>" if close
    skill_list = skills.map do |skill|
      prepend + skill + '</span>'
    end
    raw '<div class="skills">' + skill_list.join + '</div>'
  end

  def skill_label skill
    raw "<span class='label label-success'>" + skill + '</span>'
  end
end

app/views/home/index.html.haml
%content.clearfix
  = render partial: 'shared/vacancies_resumes', locals: {vacancies: @vacancies, resumes: @resumes}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kadri
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.brand{href: "/"} Кадровое агентство
    .container-fluid
      .row-fluid
        .span2
          %ul.nav.nav-pills.nav-stacked
            %li= link_to "Главная", root_path
            %li= link_to "Резюме", resumes_path
            %li= link_to "Вакансии", vacancies_path
          %h4 Навыки:
          .skills_right
            - Skill.valid_skills.each do |skill|
              = link_to skill_label(skill.name), skill_path(skill)
          %h4 Авторизация
          .home.column.left
            - unless current_user
              .connect
                = link_to 'Зарегистрироваться', new_user_registration_path, id: 'signin_link'
              .login
                Уже зарегистрированы?
                = link_to 'Войти', new_user_session_path, id: 'signin_link'
            - else
              = link_to current_user.email, edit_user_registration_path
              = link_to "Выйти", destroy_user_session_path, method: :delete
        .span10
          = render partial: 'shared/flash', locals: {flash: flash}
          = yield

app/views/resumes/_form.html.haml
= form_for @resume, :html => { :class => 'form-horizontal' } do |f|
  - if @resume.errors.any?
    .alert.alert-error
      %button.close{data: {dismiss: 'alert'}}
        &times;
      %h5= "#{pluralize(@resume.errors.count, "error")} prohibited this resume from being saved:"
      %ul
        - @resume.errors.full_messages.each do |msg|
          %li.text-error= msg
  .control-group
    = f.label :name, 'Ф.И.О.', :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field', value: params[:action] == 'new' ? current_user.name : f.object.name
  .control-group
    = f.label :status, 'Стутус', :class => 'control-label'
    .controls
      = f.select :status, options_for_select([['Ищу работу', 1], ['Не ищу', 0]], @resume.status ? 1 : 0), :class => 'number_field'
  .control-group
    = f.label :salary, 'Зарплата', :class => 'control-label'
    .controls
      = f.number_field :salary, :class => 'number_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field', value: params[:action] == 'new' ? current_user.email : f.object.email
  .control-group
    = f.label :phone, 'Тел.', :class => 'control-label'
    .controls
      = f.text_field :phone, :class => 'text_field'
  .control-group
    = f.label :skill_list, 'Навыки', :class => 'control-label'
    .controls
      = autocomplete_field_tag 'skill', '', autocomplete_skill_name_skills_path, :size => 75
      %a#add_skill{href: '#'}
        %i.icon-plus
    = f.hidden_field :skill_list, value: @resume.skill_list.join(','), class: 'skill_list'
  = skills_label(@resume.skill_list, true)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), resumes_path, :class => 'btn'

app/views/resumes/create.js.haml
$('.skills').empty().append("#{j skills_label(@resume.skill_list)}");
skills.setupForm();

app/views/resumes/edit.html.haml
- model_class = Resume
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/resumes/index.html.haml
- model_class = Resume
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= 'Ф.И.О.'
      %th= 'Зарплата'
      %th= 'Создано'
      %th
  %tbody
    - @resumes.each do |resume|
      %tr
        %td= resume.name
        %td= resume.salary
        %td= l resume.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), resume_path(resume), :class => 'btn btn-mini btn-success'
          - if can? :manage, resume
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_resume_path(resume), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), resume_path(resume), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_resume_path, :class => 'btn btn-primary'

app/views/resumes/new.html.haml
- model_class = Resume
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/resumes/show.html.haml
- model_class = Resume
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong Ф.И.О.:
  = @resume.name
%p
  %strong Статус:
  = @resume.status ? 'Ищу работу' : 'Не ищу'
%p
  %strong Зарплата:
  = @resume.salary
%p
  %strong Email:
  = @resume.email
%p
  %strong Тел.:
  = @resume.phone
%p
  %strong Навыки:
  = skills_label(@resume.skill_list)
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), resumes_path, :class => 'btn'
  - if can? :manage, @resume
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_resume_path(@resume), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), resume_path(@resume), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.row
  .span6
    %h2
      Полностью подходят
  .span6
    %h2
      Частично подходят
.row
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Название'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - @resume.fully_matched_resumes.each do |vacancy|
          %tr
            %td= vacancy.name
            %td= vacancy.salary
            %td=l vacancy.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), vacancy_path(vacancy), :class => 'btn btn-mini btn-success'
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Название'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - @resume.partially_matched_resumes.each do |vacancy|
          %tr
            %td= vacancy.name
            %td= vacancy.salary
            %td=l vacancy.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), vacancy_path(vacancy), :class => 'btn btn-mini btn-success'

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert.fade.in.remove{class: "alert-#{name}"}
      %a.close{data: {dismiss: :alert}} ×
      .msg
        = msg

app/views/shared/_vacancies_resumes.html.haml
.row
  .span6
    %h2
      - if params[:controller] == 'home'
        Последние вакансии
      - else
        Вакансии
  .span6
    %h2
      - if params[:controller] == 'home'
        Последние резюме
      - else
        Резюме
.row
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Название'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - vacancies.each do |vacancy|
          %tr
            %td= vacancy.name
            %td= vacancy.salary
            %td=l vacancy.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), vacancy_path(vacancy), :class => 'btn btn-mini btn-success'
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Ф.И.О.'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - resumes.each do |resume|
          %tr
            %td= resume.name
            %td= resume.salary
            %td= l resume.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), resume_path(resume), :class => 'btn btn-mini btn-success'

app/views/skills/show.html.haml
- model_class = Skill
.page-header
  %h1= "Умение - #{@skill.name}"

= render partial: 'shared/vacancies_resumes', locals: {vacancies: @skill.vacancies, resumes: @skill.resumes}

app/views/vacancies/_form.html.haml
= form_for @vacancy, :html => { :class => 'form-horizontal' } do |f|
  - if @vacancy.errors.any?
    .alert.alert-error
      %button.close{data: {dismiss: 'alert'}}
        &times;
      %h5= "#{pluralize(@vacancy.errors.count, "error")} prohibited this vacancy from being saved:"
      %ul
        - @vacancy.errors.full_messages.each do |msg|
          %li.text-error= msg
  .control-group
    = f.label :name, 'Название', :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :duedate, 'Срок действия', :class => 'control-label'
    .controls
      = f.text_field :duedate, :class => 'date_select', value: params[:action] == 'new' || params[:action] == 'create' ? Date.today.to_s : f.object.duedate
  .control-group
    = f.label :salary, 'Зарплата', :class => 'control-label'
    .controls
      = f.number_field :salary, :class => 'number_field'
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field', value: params[:action] == 'new' ? current_user.email : f.object.email
  .control-group
    = f.label :phone, 'Тел.', :class => 'control-label'
    .controls
      = f.text_field :phone, :class => 'text_field'
  .control-group
    = f.label :skill_list, 'Навыки', :class => 'control-label'
    .controls
      = autocomplete_field_tag 'skill', '', autocomplete_skill_name_skills_path, :size => 75
      %a#add_skill{href: '#'}
        %i.icon-plus
    = f.hidden_field :skill_list, value: @vacancy.skill_list.join(','), class: 'skill_list'
  = skills_label(@vacancy.skill_list, true)
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), vacancies_path, :class => 'btn'

app/views/vacancies/create.js.haml
$('.skills').empty().append("#{j skills_label(@resume.skill_list)}");
skills.setupForm();

app/views/vacancies/edit.html.haml
- model_class = Vacancy
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/vacancies/index.html.haml
- model_class = Vacancy
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= 'Название'
      %th= 'Зарплата'
      %th= 'Создано'
      %th
  %tbody
    - @vacancies.each do |vacancy|
      %tr
        %td= vacancy.name
        %td= vacancy.salary
        %td=l vacancy.created_at
        %td
          = link_to t('.show', :default => t("helpers.links.show")), vacancy_path(vacancy), :class => 'btn btn-mini btn-success'
          - if can? :manage, vacancy
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_vacancy_path(vacancy), :class => 'btn btn-mini'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), vacancy_path(vacancy), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_vacancy_path, :class => 'btn btn-primary'

app/views/vacancies/new.html.haml
- model_class = Vacancy
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/vacancies/show.html.haml
- model_class = Vacancy
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong Название:
  = @vacancy.name
%p
  %strong Срок действия:
  = @vacancy.duedate
%p
  %strong Зарплата:
  = @vacancy.salary
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  = @vacancy.email
%p
  %strong Тел.:
  = @vacancy.phone
%p
  %strong Навыки:
  = skills_label(@vacancy.skill_list)
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), vacancies_path, :class => 'btn'
  - if can? :manage, @vacancy
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_vacancy_path(@vacancy), :class => 'btn'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), vacancy_path(@vacancy), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

.row
  .span6
    %h2
      Полностью подходят
  .span6
    %h2
      Частично подходят
.row
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Ф.И.О.'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - @vacancy.fully_matched_vacancies.each do |resume|
          %tr
            %td= resume.name
            %td= resume.salary
            %td= l resume.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), resume_path(resume), :class => 'btn btn-mini btn-success'
  .span6
    %table.table.table-striped
      %thead
        %tr
          %th= 'Ф.И.О.'
          %th= 'Зарплата'
          %th= 'Создано'
          %th
      %tbody
        - @vacancy.partially_matched_vacancies.each do |resume|
          %tr
            %td= resume.name
            %td= resume.salary
            %td= l resume.created_at
            %td
              = link_to t('.show', :default => t("helpers.links.show")), resume_path(resume), :class => 'btn btn-mini btn-success'